# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/sdu/src/old

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/sdu/src/old

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/sdu/src/old/CMakeFiles /home/sdu/src/old/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/sdu/src/old/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named xmrig

# Build rule for target.
xmrig: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 xmrig
.PHONY : xmrig

# fast build rule for target.
xmrig/fast:
	$(MAKE) -f CMakeFiles/xmrig.dir/build.make CMakeFiles/xmrig.dir/build
.PHONY : xmrig/fast

#=============================================================================
# Target rules for targets named jansson

# Build rule for target.
jansson: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 jansson
.PHONY : jansson

# fast build rule for target.
jansson/fast:
	$(MAKE) -f compat/jansson/CMakeFiles/jansson.dir/build.make compat/jansson/CMakeFiles/jansson.dir/build
.PHONY : jansson/fast

#=============================================================================
# Target rules for targets named cpuid

# Build rule for target.
cpuid: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cpuid
.PHONY : cpuid

# fast build rule for target.
cpuid/fast:
	$(MAKE) -f compat/libcpuid/CMakeFiles/cpuid.dir/build.make compat/libcpuid/CMakeFiles/cpuid.dir/build
.PHONY : cpuid/fast

algo/cryptonight-lite/cryptonight_lite_av1_aesni.o: algo/cryptonight-lite/cryptonight_lite_av1_aesni.c.o

.PHONY : algo/cryptonight-lite/cryptonight_lite_av1_aesni.o

# target to build an object file
algo/cryptonight-lite/cryptonight_lite_av1_aesni.c.o:
	$(MAKE) -f CMakeFiles/xmrig.dir/build.make CMakeFiles/xmrig.dir/algo/cryptonight-lite/cryptonight_lite_av1_aesni.c.o
.PHONY : algo/cryptonight-lite/cryptonight_lite_av1_aesni.c.o

algo/cryptonight-lite/cryptonight_lite_av1_aesni.i: algo/cryptonight-lite/cryptonight_lite_av1_aesni.c.i

.PHONY : algo/cryptonight-lite/cryptonight_lite_av1_aesni.i

# target to preprocess a source file
algo/cryptonight-lite/cryptonight_lite_av1_aesni.c.i:
	$(MAKE) -f CMakeFiles/xmrig.dir/build.make CMakeFiles/xmrig.dir/algo/cryptonight-lite/cryptonight_lite_av1_aesni.c.i
.PHONY : algo/cryptonight-lite/cryptonight_lite_av1_aesni.c.i

algo/cryptonight-lite/cryptonight_lite_av1_aesni.s: algo/cryptonight-lite/cryptonight_lite_av1_aesni.c.s

.PHONY : algo/cryptonight-lite/cryptonight_lite_av1_aesni.s

# target to generate assembly for a file
algo/cryptonight-lite/cryptonight_lite_av1_aesni.c.s:
	$(MAKE) -f CMakeFiles/xmrig.dir/build.make CMakeFiles/xmrig.dir/algo/cryptonight-lite/cryptonight_lite_av1_aesni.c.s
.PHONY : algo/cryptonight-lite/cryptonight_lite_av1_aesni.c.s

algo/cryptonight-lite/cryptonight_lite_av2_aesni_double.o: algo/cryptonight-lite/cryptonight_lite_av2_aesni_double.c.o

.PHONY : algo/cryptonight-lite/cryptonight_lite_av2_aesni_double.o

# target to build an object file
algo/cryptonight-lite/cryptonight_lite_av2_aesni_double.c.o:
	$(MAKE) -f CMakeFiles/xmrig.dir/build.make CMakeFiles/xmrig.dir/algo/cryptonight-lite/cryptonight_lite_av2_aesni_double.c.o
.PHONY : algo/cryptonight-lite/cryptonight_lite_av2_aesni_double.c.o

algo/cryptonight-lite/cryptonight_lite_av2_aesni_double.i: algo/cryptonight-lite/cryptonight_lite_av2_aesni_double.c.i

.PHONY : algo/cryptonight-lite/cryptonight_lite_av2_aesni_double.i

# target to preprocess a source file
algo/cryptonight-lite/cryptonight_lite_av2_aesni_double.c.i:
	$(MAKE) -f CMakeFiles/xmrig.dir/build.make CMakeFiles/xmrig.dir/algo/cryptonight-lite/cryptonight_lite_av2_aesni_double.c.i
.PHONY : algo/cryptonight-lite/cryptonight_lite_av2_aesni_double.c.i

algo/cryptonight-lite/cryptonight_lite_av2_aesni_double.s: algo/cryptonight-lite/cryptonight_lite_av2_aesni_double.c.s

.PHONY : algo/cryptonight-lite/cryptonight_lite_av2_aesni_double.s

# target to generate assembly for a file
algo/cryptonight-lite/cryptonight_lite_av2_aesni_double.c.s:
	$(MAKE) -f CMakeFiles/xmrig.dir/build.make CMakeFiles/xmrig.dir/algo/cryptonight-lite/cryptonight_lite_av2_aesni_double.c.s
.PHONY : algo/cryptonight-lite/cryptonight_lite_av2_aesni_double.c.s

algo/cryptonight-lite/cryptonight_lite_av3_softaes.o: algo/cryptonight-lite/cryptonight_lite_av3_softaes.c.o

.PHONY : algo/cryptonight-lite/cryptonight_lite_av3_softaes.o

# target to build an object file
algo/cryptonight-lite/cryptonight_lite_av3_softaes.c.o:
	$(MAKE) -f CMakeFiles/xmrig.dir/build.make CMakeFiles/xmrig.dir/algo/cryptonight-lite/cryptonight_lite_av3_softaes.c.o
.PHONY : algo/cryptonight-lite/cryptonight_lite_av3_softaes.c.o

algo/cryptonight-lite/cryptonight_lite_av3_softaes.i: algo/cryptonight-lite/cryptonight_lite_av3_softaes.c.i

.PHONY : algo/cryptonight-lite/cryptonight_lite_av3_softaes.i

# target to preprocess a source file
algo/cryptonight-lite/cryptonight_lite_av3_softaes.c.i:
	$(MAKE) -f CMakeFiles/xmrig.dir/build.make CMakeFiles/xmrig.dir/algo/cryptonight-lite/cryptonight_lite_av3_softaes.c.i
.PHONY : algo/cryptonight-lite/cryptonight_lite_av3_softaes.c.i

algo/cryptonight-lite/cryptonight_lite_av3_softaes.s: algo/cryptonight-lite/cryptonight_lite_av3_softaes.c.s

.PHONY : algo/cryptonight-lite/cryptonight_lite_av3_softaes.s

# target to generate assembly for a file
algo/cryptonight-lite/cryptonight_lite_av3_softaes.c.s:
	$(MAKE) -f CMakeFiles/xmrig.dir/build.make CMakeFiles/xmrig.dir/algo/cryptonight-lite/cryptonight_lite_av3_softaes.c.s
.PHONY : algo/cryptonight-lite/cryptonight_lite_av3_softaes.c.s

algo/cryptonight-lite/cryptonight_lite_av4_softaes_double.o: algo/cryptonight-lite/cryptonight_lite_av4_softaes_double.c.o

.PHONY : algo/cryptonight-lite/cryptonight_lite_av4_softaes_double.o

# target to build an object file
algo/cryptonight-lite/cryptonight_lite_av4_softaes_double.c.o:
	$(MAKE) -f CMakeFiles/xmrig.dir/build.make CMakeFiles/xmrig.dir/algo/cryptonight-lite/cryptonight_lite_av4_softaes_double.c.o
.PHONY : algo/cryptonight-lite/cryptonight_lite_av4_softaes_double.c.o

algo/cryptonight-lite/cryptonight_lite_av4_softaes_double.i: algo/cryptonight-lite/cryptonight_lite_av4_softaes_double.c.i

.PHONY : algo/cryptonight-lite/cryptonight_lite_av4_softaes_double.i

# target to preprocess a source file
algo/cryptonight-lite/cryptonight_lite_av4_softaes_double.c.i:
	$(MAKE) -f CMakeFiles/xmrig.dir/build.make CMakeFiles/xmrig.dir/algo/cryptonight-lite/cryptonight_lite_av4_softaes_double.c.i
.PHONY : algo/cryptonight-lite/cryptonight_lite_av4_softaes_double.c.i

algo/cryptonight-lite/cryptonight_lite_av4_softaes_double.s: algo/cryptonight-lite/cryptonight_lite_av4_softaes_double.c.s

.PHONY : algo/cryptonight-lite/cryptonight_lite_av4_softaes_double.s

# target to generate assembly for a file
algo/cryptonight-lite/cryptonight_lite_av4_softaes_double.c.s:
	$(MAKE) -f CMakeFiles/xmrig.dir/build.make CMakeFiles/xmrig.dir/algo/cryptonight-lite/cryptonight_lite_av4_softaes_double.c.s
.PHONY : algo/cryptonight-lite/cryptonight_lite_av4_softaes_double.c.s

algo/cryptonight/cryptonight.o: algo/cryptonight/cryptonight.c.o

.PHONY : algo/cryptonight/cryptonight.o

# target to build an object file
algo/cryptonight/cryptonight.c.o:
	$(MAKE) -f CMakeFiles/xmrig.dir/build.make CMakeFiles/xmrig.dir/algo/cryptonight/cryptonight.c.o
.PHONY : algo/cryptonight/cryptonight.c.o

algo/cryptonight/cryptonight.i: algo/cryptonight/cryptonight.c.i

.PHONY : algo/cryptonight/cryptonight.i

# target to preprocess a source file
algo/cryptonight/cryptonight.c.i:
	$(MAKE) -f CMakeFiles/xmrig.dir/build.make CMakeFiles/xmrig.dir/algo/cryptonight/cryptonight.c.i
.PHONY : algo/cryptonight/cryptonight.c.i

algo/cryptonight/cryptonight.s: algo/cryptonight/cryptonight.c.s

.PHONY : algo/cryptonight/cryptonight.s

# target to generate assembly for a file
algo/cryptonight/cryptonight.c.s:
	$(MAKE) -f CMakeFiles/xmrig.dir/build.make CMakeFiles/xmrig.dir/algo/cryptonight/cryptonight.c.s
.PHONY : algo/cryptonight/cryptonight.c.s

algo/cryptonight/cryptonight_av1_aesni.o: algo/cryptonight/cryptonight_av1_aesni.c.o

.PHONY : algo/cryptonight/cryptonight_av1_aesni.o

# target to build an object file
algo/cryptonight/cryptonight_av1_aesni.c.o:
	$(MAKE) -f CMakeFiles/xmrig.dir/build.make CMakeFiles/xmrig.dir/algo/cryptonight/cryptonight_av1_aesni.c.o
.PHONY : algo/cryptonight/cryptonight_av1_aesni.c.o

algo/cryptonight/cryptonight_av1_aesni.i: algo/cryptonight/cryptonight_av1_aesni.c.i

.PHONY : algo/cryptonight/cryptonight_av1_aesni.i

# target to preprocess a source file
algo/cryptonight/cryptonight_av1_aesni.c.i:
	$(MAKE) -f CMakeFiles/xmrig.dir/build.make CMakeFiles/xmrig.dir/algo/cryptonight/cryptonight_av1_aesni.c.i
.PHONY : algo/cryptonight/cryptonight_av1_aesni.c.i

algo/cryptonight/cryptonight_av1_aesni.s: algo/cryptonight/cryptonight_av1_aesni.c.s

.PHONY : algo/cryptonight/cryptonight_av1_aesni.s

# target to generate assembly for a file
algo/cryptonight/cryptonight_av1_aesni.c.s:
	$(MAKE) -f CMakeFiles/xmrig.dir/build.make CMakeFiles/xmrig.dir/algo/cryptonight/cryptonight_av1_aesni.c.s
.PHONY : algo/cryptonight/cryptonight_av1_aesni.c.s

algo/cryptonight/cryptonight_av2_aesni_double.o: algo/cryptonight/cryptonight_av2_aesni_double.c.o

.PHONY : algo/cryptonight/cryptonight_av2_aesni_double.o

# target to build an object file
algo/cryptonight/cryptonight_av2_aesni_double.c.o:
	$(MAKE) -f CMakeFiles/xmrig.dir/build.make CMakeFiles/xmrig.dir/algo/cryptonight/cryptonight_av2_aesni_double.c.o
.PHONY : algo/cryptonight/cryptonight_av2_aesni_double.c.o

algo/cryptonight/cryptonight_av2_aesni_double.i: algo/cryptonight/cryptonight_av2_aesni_double.c.i

.PHONY : algo/cryptonight/cryptonight_av2_aesni_double.i

# target to preprocess a source file
algo/cryptonight/cryptonight_av2_aesni_double.c.i:
	$(MAKE) -f CMakeFiles/xmrig.dir/build.make CMakeFiles/xmrig.dir/algo/cryptonight/cryptonight_av2_aesni_double.c.i
.PHONY : algo/cryptonight/cryptonight_av2_aesni_double.c.i

algo/cryptonight/cryptonight_av2_aesni_double.s: algo/cryptonight/cryptonight_av2_aesni_double.c.s

.PHONY : algo/cryptonight/cryptonight_av2_aesni_double.s

# target to generate assembly for a file
algo/cryptonight/cryptonight_av2_aesni_double.c.s:
	$(MAKE) -f CMakeFiles/xmrig.dir/build.make CMakeFiles/xmrig.dir/algo/cryptonight/cryptonight_av2_aesni_double.c.s
.PHONY : algo/cryptonight/cryptonight_av2_aesni_double.c.s

algo/cryptonight/cryptonight_av3_softaes.o: algo/cryptonight/cryptonight_av3_softaes.c.o

.PHONY : algo/cryptonight/cryptonight_av3_softaes.o

# target to build an object file
algo/cryptonight/cryptonight_av3_softaes.c.o:
	$(MAKE) -f CMakeFiles/xmrig.dir/build.make CMakeFiles/xmrig.dir/algo/cryptonight/cryptonight_av3_softaes.c.o
.PHONY : algo/cryptonight/cryptonight_av3_softaes.c.o

algo/cryptonight/cryptonight_av3_softaes.i: algo/cryptonight/cryptonight_av3_softaes.c.i

.PHONY : algo/cryptonight/cryptonight_av3_softaes.i

# target to preprocess a source file
algo/cryptonight/cryptonight_av3_softaes.c.i:
	$(MAKE) -f CMakeFiles/xmrig.dir/build.make CMakeFiles/xmrig.dir/algo/cryptonight/cryptonight_av3_softaes.c.i
.PHONY : algo/cryptonight/cryptonight_av3_softaes.c.i

algo/cryptonight/cryptonight_av3_softaes.s: algo/cryptonight/cryptonight_av3_softaes.c.s

.PHONY : algo/cryptonight/cryptonight_av3_softaes.s

# target to generate assembly for a file
algo/cryptonight/cryptonight_av3_softaes.c.s:
	$(MAKE) -f CMakeFiles/xmrig.dir/build.make CMakeFiles/xmrig.dir/algo/cryptonight/cryptonight_av3_softaes.c.s
.PHONY : algo/cryptonight/cryptonight_av3_softaes.c.s

algo/cryptonight/cryptonight_av4_softaes_double.o: algo/cryptonight/cryptonight_av4_softaes_double.c.o

.PHONY : algo/cryptonight/cryptonight_av4_softaes_double.o

# target to build an object file
algo/cryptonight/cryptonight_av4_softaes_double.c.o:
	$(MAKE) -f CMakeFiles/xmrig.dir/build.make CMakeFiles/xmrig.dir/algo/cryptonight/cryptonight_av4_softaes_double.c.o
.PHONY : algo/cryptonight/cryptonight_av4_softaes_double.c.o

algo/cryptonight/cryptonight_av4_softaes_double.i: algo/cryptonight/cryptonight_av4_softaes_double.c.i

.PHONY : algo/cryptonight/cryptonight_av4_softaes_double.i

# target to preprocess a source file
algo/cryptonight/cryptonight_av4_softaes_double.c.i:
	$(MAKE) -f CMakeFiles/xmrig.dir/build.make CMakeFiles/xmrig.dir/algo/cryptonight/cryptonight_av4_softaes_double.c.i
.PHONY : algo/cryptonight/cryptonight_av4_softaes_double.c.i

algo/cryptonight/cryptonight_av4_softaes_double.s: algo/cryptonight/cryptonight_av4_softaes_double.c.s

.PHONY : algo/cryptonight/cryptonight_av4_softaes_double.s

# target to generate assembly for a file
algo/cryptonight/cryptonight_av4_softaes_double.c.s:
	$(MAKE) -f CMakeFiles/xmrig.dir/build.make CMakeFiles/xmrig.dir/algo/cryptonight/cryptonight_av4_softaes_double.c.s
.PHONY : algo/cryptonight/cryptonight_av4_softaes_double.c.s

cpu.o: cpu.c.o

.PHONY : cpu.o

# target to build an object file
cpu.c.o:
	$(MAKE) -f CMakeFiles/xmrig.dir/build.make CMakeFiles/xmrig.dir/cpu.c.o
.PHONY : cpu.c.o

cpu.i: cpu.c.i

.PHONY : cpu.i

# target to preprocess a source file
cpu.c.i:
	$(MAKE) -f CMakeFiles/xmrig.dir/build.make CMakeFiles/xmrig.dir/cpu.c.i
.PHONY : cpu.c.i

cpu.s: cpu.c.s

.PHONY : cpu.s

# target to generate assembly for a file
cpu.c.s:
	$(MAKE) -f CMakeFiles/xmrig.dir/build.make CMakeFiles/xmrig.dir/cpu.c.s
.PHONY : cpu.c.s

crypto/c_blake256.o: crypto/c_blake256.c.o

.PHONY : crypto/c_blake256.o

# target to build an object file
crypto/c_blake256.c.o:
	$(MAKE) -f CMakeFiles/xmrig.dir/build.make CMakeFiles/xmrig.dir/crypto/c_blake256.c.o
.PHONY : crypto/c_blake256.c.o

crypto/c_blake256.i: crypto/c_blake256.c.i

.PHONY : crypto/c_blake256.i

# target to preprocess a source file
crypto/c_blake256.c.i:
	$(MAKE) -f CMakeFiles/xmrig.dir/build.make CMakeFiles/xmrig.dir/crypto/c_blake256.c.i
.PHONY : crypto/c_blake256.c.i

crypto/c_blake256.s: crypto/c_blake256.c.s

.PHONY : crypto/c_blake256.s

# target to generate assembly for a file
crypto/c_blake256.c.s:
	$(MAKE) -f CMakeFiles/xmrig.dir/build.make CMakeFiles/xmrig.dir/crypto/c_blake256.c.s
.PHONY : crypto/c_blake256.c.s

crypto/c_groestl.o: crypto/c_groestl.c.o

.PHONY : crypto/c_groestl.o

# target to build an object file
crypto/c_groestl.c.o:
	$(MAKE) -f CMakeFiles/xmrig.dir/build.make CMakeFiles/xmrig.dir/crypto/c_groestl.c.o
.PHONY : crypto/c_groestl.c.o

crypto/c_groestl.i: crypto/c_groestl.c.i

.PHONY : crypto/c_groestl.i

# target to preprocess a source file
crypto/c_groestl.c.i:
	$(MAKE) -f CMakeFiles/xmrig.dir/build.make CMakeFiles/xmrig.dir/crypto/c_groestl.c.i
.PHONY : crypto/c_groestl.c.i

crypto/c_groestl.s: crypto/c_groestl.c.s

.PHONY : crypto/c_groestl.s

# target to generate assembly for a file
crypto/c_groestl.c.s:
	$(MAKE) -f CMakeFiles/xmrig.dir/build.make CMakeFiles/xmrig.dir/crypto/c_groestl.c.s
.PHONY : crypto/c_groestl.c.s

crypto/c_jh.o: crypto/c_jh.c.o

.PHONY : crypto/c_jh.o

# target to build an object file
crypto/c_jh.c.o:
	$(MAKE) -f CMakeFiles/xmrig.dir/build.make CMakeFiles/xmrig.dir/crypto/c_jh.c.o
.PHONY : crypto/c_jh.c.o

crypto/c_jh.i: crypto/c_jh.c.i

.PHONY : crypto/c_jh.i

# target to preprocess a source file
crypto/c_jh.c.i:
	$(MAKE) -f CMakeFiles/xmrig.dir/build.make CMakeFiles/xmrig.dir/crypto/c_jh.c.i
.PHONY : crypto/c_jh.c.i

crypto/c_jh.s: crypto/c_jh.c.s

.PHONY : crypto/c_jh.s

# target to generate assembly for a file
crypto/c_jh.c.s:
	$(MAKE) -f CMakeFiles/xmrig.dir/build.make CMakeFiles/xmrig.dir/crypto/c_jh.c.s
.PHONY : crypto/c_jh.c.s

crypto/c_keccak.o: crypto/c_keccak.c.o

.PHONY : crypto/c_keccak.o

# target to build an object file
crypto/c_keccak.c.o:
	$(MAKE) -f CMakeFiles/xmrig.dir/build.make CMakeFiles/xmrig.dir/crypto/c_keccak.c.o
.PHONY : crypto/c_keccak.c.o

crypto/c_keccak.i: crypto/c_keccak.c.i

.PHONY : crypto/c_keccak.i

# target to preprocess a source file
crypto/c_keccak.c.i:
	$(MAKE) -f CMakeFiles/xmrig.dir/build.make CMakeFiles/xmrig.dir/crypto/c_keccak.c.i
.PHONY : crypto/c_keccak.c.i

crypto/c_keccak.s: crypto/c_keccak.c.s

.PHONY : crypto/c_keccak.s

# target to generate assembly for a file
crypto/c_keccak.c.s:
	$(MAKE) -f CMakeFiles/xmrig.dir/build.make CMakeFiles/xmrig.dir/crypto/c_keccak.c.s
.PHONY : crypto/c_keccak.c.s

crypto/c_skein.o: crypto/c_skein.c.o

.PHONY : crypto/c_skein.o

# target to build an object file
crypto/c_skein.c.o:
	$(MAKE) -f CMakeFiles/xmrig.dir/build.make CMakeFiles/xmrig.dir/crypto/c_skein.c.o
.PHONY : crypto/c_skein.c.o

crypto/c_skein.i: crypto/c_skein.c.i

.PHONY : crypto/c_skein.i

# target to preprocess a source file
crypto/c_skein.c.i:
	$(MAKE) -f CMakeFiles/xmrig.dir/build.make CMakeFiles/xmrig.dir/crypto/c_skein.c.i
.PHONY : crypto/c_skein.c.i

crypto/c_skein.s: crypto/c_skein.c.s

.PHONY : crypto/c_skein.s

# target to generate assembly for a file
crypto/c_skein.c.s:
	$(MAKE) -f CMakeFiles/xmrig.dir/build.make CMakeFiles/xmrig.dir/crypto/c_skein.c.s
.PHONY : crypto/c_skein.c.s

crypto/soft_aes.o: crypto/soft_aes.c.o

.PHONY : crypto/soft_aes.o

# target to build an object file
crypto/soft_aes.c.o:
	$(MAKE) -f CMakeFiles/xmrig.dir/build.make CMakeFiles/xmrig.dir/crypto/soft_aes.c.o
.PHONY : crypto/soft_aes.c.o

crypto/soft_aes.i: crypto/soft_aes.c.i

.PHONY : crypto/soft_aes.i

# target to preprocess a source file
crypto/soft_aes.c.i:
	$(MAKE) -f CMakeFiles/xmrig.dir/build.make CMakeFiles/xmrig.dir/crypto/soft_aes.c.i
.PHONY : crypto/soft_aes.c.i

crypto/soft_aes.s: crypto/soft_aes.c.s

.PHONY : crypto/soft_aes.s

# target to generate assembly for a file
crypto/soft_aes.c.s:
	$(MAKE) -f CMakeFiles/xmrig.dir/build.make CMakeFiles/xmrig.dir/crypto/soft_aes.c.s
.PHONY : crypto/soft_aes.c.s

memory.o: memory.c.o

.PHONY : memory.o

# target to build an object file
memory.c.o:
	$(MAKE) -f CMakeFiles/xmrig.dir/build.make CMakeFiles/xmrig.dir/memory.c.o
.PHONY : memory.c.o

memory.i: memory.c.i

.PHONY : memory.i

# target to preprocess a source file
memory.c.i:
	$(MAKE) -f CMakeFiles/xmrig.dir/build.make CMakeFiles/xmrig.dir/memory.c.i
.PHONY : memory.c.i

memory.s: memory.c.s

.PHONY : memory.s

# target to generate assembly for a file
memory.c.s:
	$(MAKE) -f CMakeFiles/xmrig.dir/build.make CMakeFiles/xmrig.dir/memory.c.s
.PHONY : memory.c.s

options.o: options.c.o

.PHONY : options.o

# target to build an object file
options.c.o:
	$(MAKE) -f CMakeFiles/xmrig.dir/build.make CMakeFiles/xmrig.dir/options.c.o
.PHONY : options.c.o

options.i: options.c.i

.PHONY : options.i

# target to preprocess a source file
options.c.i:
	$(MAKE) -f CMakeFiles/xmrig.dir/build.make CMakeFiles/xmrig.dir/options.c.i
.PHONY : options.c.i

options.s: options.c.s

.PHONY : options.s

# target to generate assembly for a file
options.c.s:
	$(MAKE) -f CMakeFiles/xmrig.dir/build.make CMakeFiles/xmrig.dir/options.c.s
.PHONY : options.c.s

stats.o: stats.c.o

.PHONY : stats.o

# target to build an object file
stats.c.o:
	$(MAKE) -f CMakeFiles/xmrig.dir/build.make CMakeFiles/xmrig.dir/stats.c.o
.PHONY : stats.c.o

stats.i: stats.c.i

.PHONY : stats.i

# target to preprocess a source file
stats.c.i:
	$(MAKE) -f CMakeFiles/xmrig.dir/build.make CMakeFiles/xmrig.dir/stats.c.i
.PHONY : stats.c.i

stats.s: stats.c.s

.PHONY : stats.s

# target to generate assembly for a file
stats.c.s:
	$(MAKE) -f CMakeFiles/xmrig.dir/build.make CMakeFiles/xmrig.dir/stats.c.s
.PHONY : stats.c.s

stratum.o: stratum.c.o

.PHONY : stratum.o

# target to build an object file
stratum.c.o:
	$(MAKE) -f CMakeFiles/xmrig.dir/build.make CMakeFiles/xmrig.dir/stratum.c.o
.PHONY : stratum.c.o

stratum.i: stratum.c.i

.PHONY : stratum.i

# target to preprocess a source file
stratum.c.i:
	$(MAKE) -f CMakeFiles/xmrig.dir/build.make CMakeFiles/xmrig.dir/stratum.c.i
.PHONY : stratum.c.i

stratum.s: stratum.c.s

.PHONY : stratum.s

# target to generate assembly for a file
stratum.c.s:
	$(MAKE) -f CMakeFiles/xmrig.dir/build.make CMakeFiles/xmrig.dir/stratum.c.s
.PHONY : stratum.c.s

unix/cpu_unix.o: unix/cpu_unix.c.o

.PHONY : unix/cpu_unix.o

# target to build an object file
unix/cpu_unix.c.o:
	$(MAKE) -f CMakeFiles/xmrig.dir/build.make CMakeFiles/xmrig.dir/unix/cpu_unix.c.o
.PHONY : unix/cpu_unix.c.o

unix/cpu_unix.i: unix/cpu_unix.c.i

.PHONY : unix/cpu_unix.i

# target to preprocess a source file
unix/cpu_unix.c.i:
	$(MAKE) -f CMakeFiles/xmrig.dir/build.make CMakeFiles/xmrig.dir/unix/cpu_unix.c.i
.PHONY : unix/cpu_unix.c.i

unix/cpu_unix.s: unix/cpu_unix.c.s

.PHONY : unix/cpu_unix.s

# target to generate assembly for a file
unix/cpu_unix.c.s:
	$(MAKE) -f CMakeFiles/xmrig.dir/build.make CMakeFiles/xmrig.dir/unix/cpu_unix.c.s
.PHONY : unix/cpu_unix.c.s

unix/memory_unix.o: unix/memory_unix.c.o

.PHONY : unix/memory_unix.o

# target to build an object file
unix/memory_unix.c.o:
	$(MAKE) -f CMakeFiles/xmrig.dir/build.make CMakeFiles/xmrig.dir/unix/memory_unix.c.o
.PHONY : unix/memory_unix.c.o

unix/memory_unix.i: unix/memory_unix.c.i

.PHONY : unix/memory_unix.i

# target to preprocess a source file
unix/memory_unix.c.i:
	$(MAKE) -f CMakeFiles/xmrig.dir/build.make CMakeFiles/xmrig.dir/unix/memory_unix.c.i
.PHONY : unix/memory_unix.c.i

unix/memory_unix.s: unix/memory_unix.c.s

.PHONY : unix/memory_unix.s

# target to generate assembly for a file
unix/memory_unix.c.s:
	$(MAKE) -f CMakeFiles/xmrig.dir/build.make CMakeFiles/xmrig.dir/unix/memory_unix.c.s
.PHONY : unix/memory_unix.c.s

unix/xmrig_unix.o: unix/xmrig_unix.c.o

.PHONY : unix/xmrig_unix.o

# target to build an object file
unix/xmrig_unix.c.o:
	$(MAKE) -f CMakeFiles/xmrig.dir/build.make CMakeFiles/xmrig.dir/unix/xmrig_unix.c.o
.PHONY : unix/xmrig_unix.c.o

unix/xmrig_unix.i: unix/xmrig_unix.c.i

.PHONY : unix/xmrig_unix.i

# target to preprocess a source file
unix/xmrig_unix.c.i:
	$(MAKE) -f CMakeFiles/xmrig.dir/build.make CMakeFiles/xmrig.dir/unix/xmrig_unix.c.i
.PHONY : unix/xmrig_unix.c.i

unix/xmrig_unix.s: unix/xmrig_unix.c.s

.PHONY : unix/xmrig_unix.s

# target to generate assembly for a file
unix/xmrig_unix.c.s:
	$(MAKE) -f CMakeFiles/xmrig.dir/build.make CMakeFiles/xmrig.dir/unix/xmrig_unix.c.s
.PHONY : unix/xmrig_unix.c.s

util.o: util.c.o

.PHONY : util.o

# target to build an object file
util.c.o:
	$(MAKE) -f CMakeFiles/xmrig.dir/build.make CMakeFiles/xmrig.dir/util.c.o
.PHONY : util.c.o

util.i: util.c.i

.PHONY : util.i

# target to preprocess a source file
util.c.i:
	$(MAKE) -f CMakeFiles/xmrig.dir/build.make CMakeFiles/xmrig.dir/util.c.i
.PHONY : util.c.i

util.s: util.c.s

.PHONY : util.s

# target to generate assembly for a file
util.c.s:
	$(MAKE) -f CMakeFiles/xmrig.dir/build.make CMakeFiles/xmrig.dir/util.c.s
.PHONY : util.c.s

utils/applog.o: utils/applog.c.o

.PHONY : utils/applog.o

# target to build an object file
utils/applog.c.o:
	$(MAKE) -f CMakeFiles/xmrig.dir/build.make CMakeFiles/xmrig.dir/utils/applog.c.o
.PHONY : utils/applog.c.o

utils/applog.i: utils/applog.c.i

.PHONY : utils/applog.i

# target to preprocess a source file
utils/applog.c.i:
	$(MAKE) -f CMakeFiles/xmrig.dir/build.make CMakeFiles/xmrig.dir/utils/applog.c.i
.PHONY : utils/applog.c.i

utils/applog.s: utils/applog.c.s

.PHONY : utils/applog.s

# target to generate assembly for a file
utils/applog.c.s:
	$(MAKE) -f CMakeFiles/xmrig.dir/build.make CMakeFiles/xmrig.dir/utils/applog.c.s
.PHONY : utils/applog.c.s

utils/summary.o: utils/summary.c.o

.PHONY : utils/summary.o

# target to build an object file
utils/summary.c.o:
	$(MAKE) -f CMakeFiles/xmrig.dir/build.make CMakeFiles/xmrig.dir/utils/summary.c.o
.PHONY : utils/summary.c.o

utils/summary.i: utils/summary.c.i

.PHONY : utils/summary.i

# target to preprocess a source file
utils/summary.c.i:
	$(MAKE) -f CMakeFiles/xmrig.dir/build.make CMakeFiles/xmrig.dir/utils/summary.c.i
.PHONY : utils/summary.c.i

utils/summary.s: utils/summary.c.s

.PHONY : utils/summary.s

# target to generate assembly for a file
utils/summary.c.s:
	$(MAKE) -f CMakeFiles/xmrig.dir/build.make CMakeFiles/xmrig.dir/utils/summary.c.s
.PHONY : utils/summary.c.s

xmrig.o: xmrig.c.o

.PHONY : xmrig.o

# target to build an object file
xmrig.c.o:
	$(MAKE) -f CMakeFiles/xmrig.dir/build.make CMakeFiles/xmrig.dir/xmrig.c.o
.PHONY : xmrig.c.o

xmrig.i: xmrig.c.i

.PHONY : xmrig.i

# target to preprocess a source file
xmrig.c.i:
	$(MAKE) -f CMakeFiles/xmrig.dir/build.make CMakeFiles/xmrig.dir/xmrig.c.i
.PHONY : xmrig.c.i

xmrig.s: xmrig.c.s

.PHONY : xmrig.s

# target to generate assembly for a file
xmrig.c.s:
	$(MAKE) -f CMakeFiles/xmrig.dir/build.make CMakeFiles/xmrig.dir/xmrig.c.s
.PHONY : xmrig.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... xmrig"
	@echo "... edit_cache"
	@echo "... jansson"
	@echo "... cpuid"
	@echo "... algo/cryptonight-lite/cryptonight_lite_av1_aesni.o"
	@echo "... algo/cryptonight-lite/cryptonight_lite_av1_aesni.i"
	@echo "... algo/cryptonight-lite/cryptonight_lite_av1_aesni.s"
	@echo "... algo/cryptonight-lite/cryptonight_lite_av2_aesni_double.o"
	@echo "... algo/cryptonight-lite/cryptonight_lite_av2_aesni_double.i"
	@echo "... algo/cryptonight-lite/cryptonight_lite_av2_aesni_double.s"
	@echo "... algo/cryptonight-lite/cryptonight_lite_av3_softaes.o"
	@echo "... algo/cryptonight-lite/cryptonight_lite_av3_softaes.i"
	@echo "... algo/cryptonight-lite/cryptonight_lite_av3_softaes.s"
	@echo "... algo/cryptonight-lite/cryptonight_lite_av4_softaes_double.o"
	@echo "... algo/cryptonight-lite/cryptonight_lite_av4_softaes_double.i"
	@echo "... algo/cryptonight-lite/cryptonight_lite_av4_softaes_double.s"
	@echo "... algo/cryptonight/cryptonight.o"
	@echo "... algo/cryptonight/cryptonight.i"
	@echo "... algo/cryptonight/cryptonight.s"
	@echo "... algo/cryptonight/cryptonight_av1_aesni.o"
	@echo "... algo/cryptonight/cryptonight_av1_aesni.i"
	@echo "... algo/cryptonight/cryptonight_av1_aesni.s"
	@echo "... algo/cryptonight/cryptonight_av2_aesni_double.o"
	@echo "... algo/cryptonight/cryptonight_av2_aesni_double.i"
	@echo "... algo/cryptonight/cryptonight_av2_aesni_double.s"
	@echo "... algo/cryptonight/cryptonight_av3_softaes.o"
	@echo "... algo/cryptonight/cryptonight_av3_softaes.i"
	@echo "... algo/cryptonight/cryptonight_av3_softaes.s"
	@echo "... algo/cryptonight/cryptonight_av4_softaes_double.o"
	@echo "... algo/cryptonight/cryptonight_av4_softaes_double.i"
	@echo "... algo/cryptonight/cryptonight_av4_softaes_double.s"
	@echo "... cpu.o"
	@echo "... cpu.i"
	@echo "... cpu.s"
	@echo "... crypto/c_blake256.o"
	@echo "... crypto/c_blake256.i"
	@echo "... crypto/c_blake256.s"
	@echo "... crypto/c_groestl.o"
	@echo "... crypto/c_groestl.i"
	@echo "... crypto/c_groestl.s"
	@echo "... crypto/c_jh.o"
	@echo "... crypto/c_jh.i"
	@echo "... crypto/c_jh.s"
	@echo "... crypto/c_keccak.o"
	@echo "... crypto/c_keccak.i"
	@echo "... crypto/c_keccak.s"
	@echo "... crypto/c_skein.o"
	@echo "... crypto/c_skein.i"
	@echo "... crypto/c_skein.s"
	@echo "... crypto/soft_aes.o"
	@echo "... crypto/soft_aes.i"
	@echo "... crypto/soft_aes.s"
	@echo "... memory.o"
	@echo "... memory.i"
	@echo "... memory.s"
	@echo "... options.o"
	@echo "... options.i"
	@echo "... options.s"
	@echo "... stats.o"
	@echo "... stats.i"
	@echo "... stats.s"
	@echo "... stratum.o"
	@echo "... stratum.i"
	@echo "... stratum.s"
	@echo "... unix/cpu_unix.o"
	@echo "... unix/cpu_unix.i"
	@echo "... unix/cpu_unix.s"
	@echo "... unix/memory_unix.o"
	@echo "... unix/memory_unix.i"
	@echo "... unix/memory_unix.s"
	@echo "... unix/xmrig_unix.o"
	@echo "... unix/xmrig_unix.i"
	@echo "... unix/xmrig_unix.s"
	@echo "... util.o"
	@echo "... util.i"
	@echo "... util.s"
	@echo "... utils/applog.o"
	@echo "... utils/applog.i"
	@echo "... utils/applog.s"
	@echo "... utils/summary.o"
	@echo "... utils/summary.i"
	@echo "... utils/summary.s"
	@echo "... xmrig.o"
	@echo "... xmrig.i"
	@echo "... xmrig.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

